### ISSUE TITLE
'Gtk was imported without specifying a version first' error - GTK 4?

### ISSUE THREAD

**Issue by Skepller** [z411/trackma#622] opened 2022-07-01 10:19 UTC
Specs:

**OS**: Pop!_OS 22.04 LTS x86_64
**Kernel**: 5.17.15-76051715-generic
**Shell**: bash 5.1.16
**DE**: GNOME 42.2
**CPU**: Intel i7-10750H (12) @ 5.000GHz
**GPU**: NVIDIA GeForce RTX 2060 Mobile 
**Memory**: 16Gb

Error when launching for the first time:

```
skepller@skepller:~$ pip3 install Trackma
Defaulting to user installation because normal site-packages is not writeable
Collecting Trackma
  Downloading Trackma-0.8.4-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 KB 3.9 MB/s eta 0:00:00
Installing collected packages: Trackma
Successfully installed Trackma-0.8.4


skepller@skepller:~$ trackma
trackma         trackma-curses  trackma-gtk     trackma-qt      trackma-qt4


skepller@skepller:~$ trackma-gtk
/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Traceback (most recent call last):
  File "/home/skepller/.local/bin/trackma-gtk", line 5, in <module>
    from trackma.ui.gtk.main import main
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/main.py", line 19, in <module>
    from trackma.ui.gtk.application import TrackmaApplication
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/application.py", line 18, in <module>
    from trackma.ui.gtk.window import TrackmaWindow
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/window.py", line 25, in <module>
    from trackma.ui.gtk.accountswindow import AccountsWindow
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/accountswindow.py", line 34, in <module>
    class AccountsWindow(Gtk.Dialog):
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/gi_composites.py", line 262, in __call__
    _register_template(cls, template_bytes)
  File "/home/skepller/.local/lib/python3.10/site-packages/trackma/ui/gtk/gi_composites.py", line 95, in _register_template
    cls.set_connect_func(_connect_func, cls)
AttributeError: type object 'AccountsWindow' has no attribute 'set_connect_func'
```
I have the GTK dependencies listed
```
python3-cairo is already the newest version (1.20.1-3build1).
python3-gi is already the newest version (3.42.0-3build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
---
This is not really my area, but skimming through the error, is GTK 4 not supported yet?
Funnily enough I can launch and use the Qt version for now.

**Comment by ahmubashshir** [comment] 2022-07-05 09:22
How did you install trackma?

**Comment by Skepller** [comment] 2022-07-05 09:49
I installed it with `pip3 install Trackma`
Since Gtk4 is not supported I suppose installing from source wouldn't make a difference then.

Is Gtk4 support planned?

**Comment by ahmubashshir** [comment] 2022-07-05 09:56
This was a bug that is fixed on `master` branch, try building from master first[^.]

Is Gtk4 support planned? ask @FichteFoll

[^.]: as python-gi shows that warning only when it finds more than one major release of the same library, you probably have gtk3 installed

**Comment by FichteFoll** [comment] 2022-07-06 01:09
(I actually only use the cli version, so I'm probably a bad candidate for answering that, but I personally don't plan on adding gtk4 support so long as gtk3 works.)

That said, we should ensure that the gtk ui still works when gtk4 is also installed. I cannot reproduce the issue btw and I have gtk4 installed on my system, but I also use Arch and may not have the python library that causes the conflict.

**Comment by Skepller** [comment] 2022-07-06 09:56
> This was a bug that is fixed on `master` branch, try building from master first[1](#user-content-fn-.-5fe8c9ebbd26aa0ec7d732f4b1b77e1d)

@ahmubashshir Sorry for the delayed answer, installing from git with `# pip3 install -U git+https://github.com/z411/trackma.git` **worked**, so I guess it's this bug you mentioned!

In hindsight I should have tried that before, but at least it generated this issue which might end up useful for other people later on!

@FichteFoll Apparently the bug is already fixed on master as pointed out by ahmu, just needs to update the pip package. If there's still any interest in replicating, I'm using Pop OS 22.04 and i haven't messed with the DE at all, so maybe a fresh install / live usb should be able to reproduce.

Thanks for the support!

**Comment by FichteFoll** [comment] 2022-07-06 15:54
Thanks for the confirmation, closing as fixed.

**Closed by FichteFoll** 2022-07-06 15:54 UTC
Labels: bug, ui:gtk

**Comment by ahmubashshir** [comment] 2022-10-11 07:25
He's using last stable version from pypi, which was released before Gtk 4, and Gtk 2 doesn't have gir support, so we didn't encounter this bug. It was fixed in master after Gtk 4 was released. 


Mubashshir

----- Reply message -----
From: "FichteFoll" ***@***.***>
To: "z411/trackma" ***@***.***>
Cc: "Mubashshir" ***@***.***>, "Comment" ***@***.***>
Subject: [z411/trackma] 'Gtk was imported without specifying a version first' error - GTK 4? (Issue #622)
Date: Wed, Jul 6, 2022 7:09 AM

(I actually only use the cli version, so I'm probably a bad candidate for answering that, but I personally don't plan on adding gtk4 support so long as gtk3 works.)
That said, we should ensure that the gtk ui still works when gtk4 is also installed. I cannot reproduce the issue btw and I have gtk4 installed on my system, but I also use Arch and may not have the python library that causes the conflict.

&mdash;Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by z411** [comment] 2022-10-13 06:14
I should probably release in pypi since a lot has changed.
