### ISSUE TITLE
Open containing folder of anime

### ISSUE THREAD

**Issue by Logmytech** [z411/trackma#178] opened 2015-12-01 10:03 UTC
I'd like to have the option to open the container folder of the anime in my library. And also an option to open the Library folder would be good too.

**Comment by Birdulon** [comment] 2015-12-01 15:30
Duplicate of #133.

**Comment by z411** [comment] 2015-12-01 20:46
Indeed, duplicate of #133 - Trackma assuming the directory is the place where the first or last episode is in, is the current plan.

**Closed by z411** 2015-12-01 20:46 UTC
