### ISSUE TITLE
Tracker: Plex Media Server is not running.

### ISSUE THREAD

**Issue by lolihunter** [z411/trackma#235] opened 2016-09-03 22:52 UTC
Trackma seems to not be able to detect my plex server, running on the same system.

`Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: Using Plex.
Ready.
Tracker: Plex Media Server is not running.`

I have tried using both "localhost" and my systems IP as workarounds, but I always get the same output in terminal. Port is correct, I can stream and play everything fine, so I know plex is working. Seems to be an issue with trackma.

**Comment by Hairo** [comment] 2016-12-13 19:11
It returns that message when it can't open the plex info url ( http://host:port/status/sessions ), does that url load for you?

**Comment by z411** [comment] 2017-03-31 08:25
Maybe this was fixed by #287 ?

**Comment by BradleyDS2** [comment] 2017-07-07 07:07
I currently have the same issue.

From my browser, I can access http://host:port/status/sessions, and while playing a video, it has all the information, http://host:port/library/metadata/id however returns "400 Bad Request" and http://host:port/library/metadata returns
 `<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1498592902">
</MediaContainer>`

**Comment by z411** [comment] 2017-09-18 00:44
I assume this was an issue caused by authentication not being supported; marking as fixed.

**Closed by z411** 2017-09-18 00:44 UTC
Labels: bug
