### ISSUE TITLE
More cli-friendly mode?

### ISSUE THREAD

**Issue by filo86** [z411/trackma#310] opened 2017-09-18 00:12 UTC
I mean, the commands you can use in trackma as commandline parameters? Something like `trackma --add <show> --send` ?

**Comment by z411** [comment] 2017-09-18 01:03
Something like this was suggested in #79 long time ago, but it was never implemented.

The current reasoning of the current CLI interface is that if it were a single run process:

1. The list would have to be loaded into memory every time you run it (this takes a bit of time if the list is big)
2. The tracker and other interval based tasks (like auto-send or auto-retrieve) would be unavailable

so a persistent interactive process made more sense.

To have this, and fix the first issue, is to use some kind of database for the list like SQLite for faster access, instead of the serialized list we're using now. But the better solution that fixes both issues is to have a server-client architecture, where you run Trackma as a daemon (which runs interval based tasks and the tracker) and a client program to call commands. Of course this takes more work to implement, and you'd also have to start the daemon first (or run it as a service, which might be overkill?).

There are also two ways to do the latter:
1. Create a trackma-daemon (server) and a trackma-cli (command-line client), and keep the rest of Trackma as it is
2. Change the entire architecture, that means changing the curses/GTK/Qt interfaces to work with the daemon too. Of course, this takes more work.

I like the server-client architecture myself (mpd is one of my favorite pieces of software) but I thought that (1) it might be overkill for Trackma and (2) it wouldn't be useful for many people to warrant such work. Unless anyone is interested, please let me know here.

**Comment by filo86** [comment] 2017-09-18 03:12
So....maybe an externally accesible queue (named pipe?) to inject commands? with cli interface we have now, adding a show can be done with `printf "add\n\"<show>\"\n1\nquit\n" | trackma`, but things go tricky when given title is - for example - in 'ptw' or 'completed' list.

**Comment by z411** [comment] 2017-10-02 02:06
Oh IPC. It might be another option. Either way I'll mark this as duplicate of #79, please continue discussion there, thank you.

**Closed by z411** 2017-10-02 02:06 UTC
