### ISSUE TITLE
issue with pygobject 3.26

### ISSUE THREAD

**Issue by SolarAquarion** [z411/trackma#313] opened 2017-10-02 14:10 UTC
Traceback (most recent call last):
  File "/usr/bin/trackma-gtk", line 11, in <module>
    load_entry_point('Trackma==0.7.4', 'gui_scripts', 'trackma-gtk')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygobject' distribution was not found and is required by the application

**Comment by z411** [comment] 2017-10-02 23:01
Hello, my installation seems to be working fine. What are the steps to reproduce this?

**Comment by SolarAquarion** [comment] 2017-10-08 18:18
i installed it via the arch package manager

**Comment by molkoback** [comment] 2017-10-08 19:20
You mean AUR? Trackma is not in the official repostries of Arch.
Anyway install python-gobject: pacman -S python-gobject
You should also check if you're missing any other optional dependencies: https://aur.archlinux.org/packages/trackma-git/

**Comment by SolarAquarion** [comment] 2017-10-08 19:22
Yes, I mean the aur, I installed Python-gobject via pacman

**Comment by filo86** [comment] 2017-10-08 22:11
installation of python-gobject-patched via AUR seems to get trackma-gtk to run properly

**Comment by SolarAquarion** [comment] 2017-10-08 22:31
I think something is wrong with trackma and pyobject 3.26

On Oct 8, 2017 6:11 PM, "filo86" <notifications@github.com> wrote:

installation of python-gobject-patched via AUR seems to get trackma-gtk to
run properly

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/z411/trackma/issues/313#issuecomment-335042454>, or mute
the thread

**Comment by molkoback** [comment] 2017-10-09 09:24
3.26 doesn't seem to have .egg-info

**Comment by dyskette** [comment] 2017-10-09 12:26
Indeed, in Fedora 27 beta happens too. And looking at the package information there is no egg-info file in pygobject3 3.26.

**Comment by dantempla** [comment] 2017-10-10 21:42
> installation of python-gobject-patched via AUR seems to get trackma-gtk to run properly

Is not working for me. Problem still persists.

**Comment by SolarAquarion** [comment] 2017-10-10 21:55
You need to build 3.24 and edit the missing package

**Comment by wizbright** [comment] 2017-10-20 14:56
I'm having the same issues. I pulled from git and installed and now I have the same errors.

**Comment by molkoback** [comment] 2017-10-30 18:58
Fixed in 3.26.1-1 btw.

**Closed** 2017-11-20 03:36 UTC
